// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iryhbvvehljstazahwsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyeWhidnZlaGxqc3RhemFod3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzc3MjMsImV4cCI6MjA2ODc1MzcyM30.hT_Tf5cgpmJWErgOsN9kPNoXzVQJgGeupchvPew-lTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});